server:
  port: 82
  servlet:
    context-path: /ssoserver
    session:
      timeout: 1800


spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password:
    databaseIndex: 1
    expire: 400
    maxTotal: 50000
    jedis:
      pool:
        max-active: 10
        max-idle: 20
        min-idle: 10
        max-wait: 5000

# 日志配置
logging:
  level:
    com.wayn: debug
    org.springframework: info

# sso各系统路径
sso:
  waynAdminUrl: http://127.0.0.1/wayn
