server:
  compression:
    enabled: true
    min-response-size: 1KB
  port: 80
  servlet:
    context-path: /wayn
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    # Tomcat启动初始化的线程数，默认值25
    threads:
      max: 300
      min-spare: 30

# spring
spring:
  thymeleaf:
    suffix: .html
    cache: false
    encoding: UTF-8
  profiles:
    active: dev
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false

# 配置
shiro:
  loginUrl: http://127.0.0.1:82/ssoserver/login?backUrl=http://127.0.0.1/wayn/login
  successUrl: /home
  unauthorizedUrl: /error/unauth
  retryCount: 5
  algorithmName: MD5
  iterations: 1024
  session-timeout: 1800

# wayn配置
wayn:
  name: wayn
  version: 1.1.0
  email: 166738430@qq.com
  uploadDir: E:/wayn/upload
  singeUserAuth: false
  singeKickoutBefore: true
  logHandlerCount: 3
  ssoServerUrl: http://127.0.0.1:82/ssoserver
  currentServerUrl: http://127.0.0.1/wayn
  mallUrl: http://127.0.0.1:84/mall



